apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.kafka.topic.name }}
  labels:
    {{- include "modern-devops-stack-module-kafka.labels" $ | indent 4 }}
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  topicName: {{ .Values.kafka.topic.name }}
  partitions: {{ .Values.kafka.topic.partitions }}
  replicas: {{ .Values.kafka.topic.replicas }}
  config:
    retention.ms: {{ .Values.kafka.topic.retention }}
