---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: {{ .Values.kafka.name }}
  labels:
    {{- include "modern-devops-stack-module-kafka.labels" $ | indent 4 }}
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  goals:
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - NetworkOutboundCapacityGoal
    - CpuCapacityGoal
    - ReplicaCapacityGoal
    - TopicReplicaDistributionGoal
    - MinTopicLeadersPerBrokerGoal
    - LeaderReplicaDistributionGoal
    - DiskUsageDistributionGoal
    - IntraBrokerDiskCapacityGoal
    - IntraBrokerDiskUsageDistributionGoal
